// 333 quotes — founders, inventors, builders, stoics. Carried over unchanged from the iOS app.
export const QUOTES = [
// 1–10 · Naval Ravikant
["Desire is a contract you make with yourself to be unhappy until you get what you want.","Naval Ravikant"],
["Play long-term games with long-term people.","Naval Ravikant"],
["Earn with your mind, not your time.","Naval Ravikant"],
["Specific knowledge is found by pursuing your genuine curiosity.","Naval Ravikant"],
["The most important skill for getting rich is becoming a perpetual learner.","Naval Ravikant"],
["All the real benefits in life come from compound interest.","Naval Ravikant"],
["A calm mind, a fit body, a house full of love. These things cannot be bought.","Naval Ravikant"],
["If you can't decide, the answer is no.","Naval Ravikant"],
["Escape competition through authenticity.","Naval Ravikant"],
["The modern struggle: lone individuals fighting an army of scientists optimizing for cheap dopamine.","Naval Ravikant"],
// 11–20 · Naval Ravikant
["Read what you love until you love to read.","Naval Ravikant"],
["Doctors won't make you healthy. Teachers won't make you smart. Save yourself.","Naval Ravikant"],
["You're not going to get rich renting out your time.","Naval Ravikant"],
["Impatience with actions, patience with results.","Naval Ravikant"],
["Free education is abundant. The desire to learn is scarce.","Naval Ravikant"],
["Code and media are permissionless leverage.","Naval Ravikant"],
["In an age of infinite leverage, judgment is the most important skill.","Naval Ravikant"],
["The closer you want to get to me, the better your values have to be.","Naval Ravikant"],
["Inspiration is perishable — act on it immediately.","Naval Ravikant"],
["Happiness is a skill you can learn, like fitness or nutrition.","Naval Ravikant"],
// 21–30 · Steve Jobs
["Stay hungry, stay foolish.","Steve Jobs"],
["The people who are crazy enough to think they can change the world are the ones who do.","Steve Jobs"],
["Your time is limited, so don't waste it living someone else's life.","Steve Jobs"],
["Innovation distinguishes between a leader and a follower.","Steve Jobs"],
["Quality is more important than quantity. One home run is much better than two doubles.","Steve Jobs"],
["Design is not just what it looks like and feels like. Design is how it works.","Steve Jobs"],
["Have the courage to follow your heart and intuition.","Steve Jobs"],
["About half of what separates successful entrepreneurs from the rest is pure perseverance.","Steve Jobs"],
["Focusing is about saying no.","Steve Jobs"],
["Real artists ship.","Steve Jobs"],
// 31–40 · Thomas Edison
["Genius is one percent inspiration and ninety-nine percent perspiration.","Thomas Edison"],
["I have not failed. I've just found 10,000 ways that won't work.","Thomas Edison"],
["Opportunity is missed by most people because it is dressed in overalls and looks like work.","Thomas Edison"],
["Many of life's failures are people who did not realize how close they were to success when they gave up.","Thomas Edison"],
["There is no substitute for hard work.","Thomas Edison"],
["The most certain way to succeed is always to try just one more time.","Thomas Edison"],
["The value of an idea lies in the using of it.","Thomas Edison"],
["Everything comes to him who hustles while he waits.","Thomas Edison"],
["Vision without execution is hallucination.","Thomas Edison"],
["What you are will show in what you do.","Thomas Edison"],
// 41–50 · Albert Einstein
["Imagination is more important than knowledge.","Albert Einstein"],
["In the middle of difficulty lies opportunity.","Albert Einstein"],
["Try not to become a person of success, but rather a person of value.","Albert Einstein"],
["I have no special talent. I am only passionately curious.","Albert Einstein"],
["Life is like riding a bicycle. To keep your balance, you must keep moving.","Albert Einstein"],
["A person who never made a mistake never tried anything new.","Albert Einstein"],
["It's not that I'm so smart, it's just that I stay with problems longer.","Albert Einstein"],
["The measure of intelligence is the ability to change.","Albert Einstein"],
["Once you stop learning, you start dying.","Albert Einstein"],
["Logic will get you from A to B. Imagination will take you everywhere.","Albert Einstein"],
// 51–60 · Henry Ford
["Whether you think you can, or you think you can't — you're right.","Henry Ford"],
["Failure is simply the opportunity to begin again, this time more intelligently.","Henry Ford"],
["Don't find fault, find a remedy.","Henry Ford"],
["Obstacles are those frightful things you see when you take your eyes off your goal.","Henry Ford"],
["Quality means doing it right when no one is looking.","Henry Ford"],
["If everyone is moving forward together, then success takes care of itself.","Henry Ford"],
["The only real mistake is the one from which we learn nothing.","Henry Ford"],
["Chop your own wood and it will warm you twice.","Henry Ford"],
["Anyone who stops learning is old, whether at twenty or eighty.","Henry Ford"],
["You can't build a reputation on what you are going to do.","Henry Ford"],
// 61–70 · Benjamin Franklin
["An investment in knowledge pays the best interest.","Benjamin Franklin"],
["Well done is better than well said.","Benjamin Franklin"],
["By failing to prepare, you are preparing to fail.","Benjamin Franklin"],
["Energy and persistence conquer all things.","Benjamin Franklin"],
["Lost time is never found again.","Benjamin Franklin"],
["Either write something worth reading or do something worth writing.","Benjamin Franklin"],
["Early to bed and early to rise makes a man healthy, wealthy and wise.","Benjamin Franklin"],
["He that can have patience can have what he will.","Benjamin Franklin"],
["Diligence is the mother of good luck.","Benjamin Franklin"],
["Never leave that till tomorrow which you can do today.","Benjamin Franklin"],
// 71–80 · Leonardo da Vinci
["Simplicity is the ultimate sophistication.","Leonardo da Vinci"],
["Learning never exhausts the mind.","Leonardo da Vinci"],
["People of accomplishment rarely sat back and let things happen to them. They went out and happened to things.","Leonardo da Vinci"],
["Knowing is not enough; we must apply. Being willing is not enough; we must do.","Leonardo da Vinci"],
["Obstacles cannot crush me. Every obstacle yields to stern resolve.","Leonardo da Vinci"],
["Time stays long enough for anyone who will use it.","Leonardo da Vinci"],
["The noblest pleasure is the joy of understanding.","Leonardo da Vinci"],
["Art is never finished, only abandoned.","Leonardo da Vinci"],
["Iron rusts from disuse; stagnant water loses its purity. Even so does inaction sap the vigor of the mind.","Leonardo da Vinci"],
["Make your work to be in keeping with your purpose.","Leonardo da Vinci"],
// 81–90 · Charlie Munger
["Spend each day trying to be a little wiser than you were when you woke up.","Charlie Munger"],
["The big money is not in the buying and selling, but in the waiting.","Charlie Munger"],
["Take a simple idea and take it seriously.","Charlie Munger"],
["In my whole life, I have known no wise people who didn't read all the time.","Charlie Munger"],
["It is remarkable how much long-term advantage we got by trying to be consistently not stupid.","Charlie Munger"],
["The best way to get what you want is to deserve what you want.","Charlie Munger"],
["Knowing what you don't know is more useful than being brilliant.","Charlie Munger"],
["Those who keep learning will keep rising in life.","Charlie Munger"],
["Invert, always invert.","Charlie Munger"],
["All I want to know is where I'm going to die, so I'll never go there.","Charlie Munger"],
// 91–100 · Warren Buffett
["The best investment you can make is in yourself.","Warren Buffett"],
["Price is what you pay. Value is what you get.","Warren Buffett"],
["Someone's sitting in the shade today because someone planted a tree a long time ago.","Warren Buffett"],
["It takes 20 years to build a reputation and five minutes to ruin it.","Warren Buffett"],
["Really successful people say no to almost everything.","Warren Buffett"],
["Risk comes from not knowing what you're doing.","Warren Buffett"],
["The chains of habit are too light to be felt until they are too heavy to be broken.","Warren Buffett"],
["Do not save what is left after spending, but spend what is left after saving.","Warren Buffett"],
["Honesty is a very expensive gift. Don't expect it from cheap people.","Warren Buffett"],
["Games are won by players who focus on the playing field, not the scoreboard.","Warren Buffett"],
// 101–110 · Jeff Bezos
["Your brand is what other people say about you when you're not in the room.","Jeff Bezos"],
["If you double the number of experiments you do per year, you're going to double your inventiveness.","Jeff Bezos"],
["Be stubborn on vision but flexible on details.","Jeff Bezos"],
["Life's too short to hang out with people who aren't resourceful.","Jeff Bezos"],
["In the end, we are our choices.","Jeff Bezos"],
["If you're not stubborn, you'll give up on experiments too soon.","Jeff Bezos"],
["Work hard, have fun, make history.","Jeff Bezos"],
["A good question is 'why?' An equally valid question is 'why not?'","Jeff Bezos"],
["It's always Day One.","Jeff Bezos"],
["If you only do things you know will work, you leave a lot of opportunity on the table.","Jeff Bezos"],
// 111–120 · Elon Musk & Walt Disney
["When something is important enough, you do it even if the odds are not in your favor.","Elon Musk"],
["Persistence is very important. You should not give up unless you are forced to give up.","Elon Musk"],
["If you get up in the morning and think the future is going to be better, it is a bright day.","Elon Musk"],
["Work like hell — it improves the odds of success.","Elon Musk"],
["If things are not failing, you are not innovating enough.","Elon Musk"],
["The first step is to establish that something is possible; then probability will occur.","Elon Musk"],
["People should pursue what they're passionate about.","Elon Musk"],
["Constantly seek criticism. A well thought out critique is as valuable as gold.","Elon Musk"],
["The way to get started is to quit talking and begin doing.","Walt Disney"],
["All our dreams can come true, if we have the courage to pursue them.","Walt Disney"],
// 121–130 · Walt Disney & Andrew Carnegie
["It's kind of fun to do the impossible.","Walt Disney"],
["Times change rapidly — keep your aim constantly focused on the future.","Walt Disney"],
["First, think. Second, dream. Third, believe. And finally, dare.","Walt Disney"],
["When you believe in a thing, believe in it all the way.","Walt Disney"],
["We keep moving forward, opening new doors, because curiosity keeps leading us down new paths.","Walt Disney"],
["Get a good idea and stay with it. Work at it until it's done right.","Walt Disney"],
["People who are unable to motivate themselves must be content with mediocrity.","Andrew Carnegie"],
["The first man gets the oyster, the second man gets the shell.","Andrew Carnegie"],
["As I grow older, I pay less attention to what men say. I just watch what they do.","Andrew Carnegie"],
["Concentrate your energies, your thoughts and your capital.","Andrew Carnegie"],
// 131–140 · Carnegie & Rockefeller
["Do your duty and a little more and the future will take care of itself.","Andrew Carnegie"],
["Aim for the highest.","Andrew Carnegie"],
["No man will make a great leader who wants to do it all himself.","Andrew Carnegie"],
["Don't be afraid to give up the good to go for the great.","John D. Rockefeller"],
["The secret of success is to do the common thing uncommonly well.","John D. Rockefeller"],
["I do not think there is any other quality so essential to success as perseverance.","John D. Rockefeller"],
["Singleness of purpose is one of the chief essentials for success in life.","John D. Rockefeller"],
["Find what interests you and that you can do well, and put your whole soul into it.","John D. Rockefeller"],
["Good leadership consists of showing average people how to do the work of superior people.","John D. Rockefeller"],
["I always tried to turn every disaster into an opportunity.","John D. Rockefeller"],
// 141–150 · Marcus Aurelius
["You have power over your mind — not outside events. Realize this, and you will find strength.","Marcus Aurelius"],
["The impediment to action advances action. What stands in the way becomes the way.","Marcus Aurelius"],
["Waste no more time arguing about what a good man should be. Be one.","Marcus Aurelius"],
["Very little is needed to make a happy life; it is all within yourself.","Marcus Aurelius"],
["Confine yourself to the present.","Marcus Aurelius"],
["The happiness of your life depends upon the quality of your thoughts.","Marcus Aurelius"],
["If it is not right, do not do it; if it is not true, do not say it.","Marcus Aurelius"],
["Dwell on the beauty of life. Watch the stars, and see yourself running with them.","Marcus Aurelius"],
["Think of yourself as dead. You have lived your life. Now take what's left and live it properly.","Marcus Aurelius"],
["It is not death that a man should fear, but never beginning to live.","Marcus Aurelius"],
// 151–160 · Seneca
["Luck is what happens when preparation meets opportunity.","Seneca"],
["It is not that we have a short time to live, but that we waste a lot of it.","Seneca"],
["Difficulties strengthen the mind, as labor does the body.","Seneca"],
["Every new beginning comes from some other beginning's end.","Seneca"],
["He who is brave is free.","Seneca"],
["While we are postponing, life speeds by.","Seneca"],
["Begin at once to live, and count each separate day as a separate life.","Seneca"],
["No man was ever wise by chance.","Seneca"],
["Hang on to your youthful enthusiasms — you'll be able to use them better when you're older.","Seneca"],
["We suffer more often in imagination than in reality.","Seneca"],
// 161–170 · Bruce Lee & Confucius
["I fear not the man who has practiced 10,000 kicks once, but the man who has practiced one kick 10,000 times.","Bruce Lee"],
["Be water, my friend.","Bruce Lee"],
["Absorb what is useful, discard what is not, add what is uniquely your own.","Bruce Lee"],
["Knowing is not enough, we must apply. Willing is not enough, we must do.","Bruce Lee"],
["Do not pray for an easy life, pray for the strength to endure a difficult one.","Bruce Lee"],
["Long-term consistency beats short-term intensity.","Bruce Lee"],
["If you spend too much time thinking about a thing, you'll never get it done.","Bruce Lee"],
["A goal is not always meant to be reached; it often serves simply as something to aim at.","Bruce Lee"],
["It does not matter how slowly you go as long as you do not stop.","Confucius"],
["The man who moves a mountain begins by carrying away small stones.","Confucius"],
// 171–180 · Confucius & Aristotle
["Our greatest glory is not in never falling, but in rising every time we fall.","Confucius"],
["When the goals cannot be reached, don't adjust the goals — adjust the action steps.","Confucius"],
["He who learns but does not think is lost.","Confucius"],
["Wherever you go, go with all your heart.","Confucius"],
["The superior man is modest in his speech but exceeds in his actions.","Confucius"],
["Real knowledge is to know the extent of one's ignorance.","Confucius"],
["We are what we repeatedly do. Excellence, then, is not an act, but a habit.","Aristotle"],
["Pleasure in the job puts perfection in the work.","Aristotle"],
["It is during our darkest moments that we must focus to see the light.","Aristotle"],
["The roots of education are bitter, but the fruit is sweet.","Aristotle"],
// 181–190 · Aristotle, Tesla & Chanel
["Knowing yourself is the beginning of all wisdom.","Aristotle"],
["Through discipline comes freedom.","Aristotle"],
["If you want to find the secrets of the universe, think in terms of energy, frequency and vibration.","Nikola Tesla"],
["The present is theirs; the future, for which I really worked, is mine.","Nikola Tesla"],
["I don't care that they stole my idea. I care that they don't have any of their own.","Nikola Tesla"],
["Invention is the most important product of man's creative brain.","Nikola Tesla"],
["Be alone — that is the secret of invention; that is when ideas are born.","Nikola Tesla"],
["Our virtues and our failings are inseparable, like force and matter.","Nikola Tesla"],
["In order to be irreplaceable, one must always be different.","Coco Chanel"],
["Success is most often achieved by those who don't know that failure is inevitable.","Coco Chanel"],
// 191–200 · Chanel, Lauder, Ferrari & Walton
["Don't spend time beating on a wall, hoping to transform it into a door.","Coco Chanel"],
["The most courageous act is still to think for yourself. Aloud.","Coco Chanel"],
["Simplicity is the keynote of all true elegance.","Coco Chanel"],
["I never dreamed about success. I worked for it.","Estée Lauder"],
["When you stop talking, you've lost your customer.","Estée Lauder"],
["I didn't get there by wishing for it or hoping for it, but by working for it.","Estée Lauder"],
["Aerodynamics are for people who can't build engines.","Enzo Ferrari"],
["The best Ferrari ever made is the next one.","Enzo Ferrari"],
["You cannot describe passion, you can only live it.","Enzo Ferrari"],
["High expectations are the key to everything.","Sam Walton"],
// 201–210 · Walton, Kroc, Coolidge & Knight
["Outstanding leaders go out of their way to boost the self-esteem of their personnel.","Sam Walton"],
["Celebrate your successes. Find some humor in your failures.","Sam Walton"],
["Capital isn't scarce; vision is.","Sam Walton"],
["There is only one boss: the customer.","Sam Walton"],
["Commit to your business. Believe in it more than anybody else.","Sam Walton"],
["Luck is a dividend of sweat. The more you sweat, the luckier you get.","Ray Kroc"],
["Major success requires being in the right place at the right time — and doing something about it.","Ray Kroc"],
["Nothing in the world can take the place of persistence.","Calvin Coolidge"],
["If you work just for money, you'll never make it. Love what you're doing, and success will be yours.","Ray Kroc"],
["The cowards never started and the weak died along the way. That leaves us.","Phil Knight"],
// 211–220 · Knight, Patton, Branson & Oprah
["Tell people what to do, not how to do it, and let them surprise you with their results.","George S. Patton"],
["Play by the rules, but be ferocious.","Phil Knight"],
["Dream audaciously. Have the courage to fail forward.","Phil Knight"],
["Screw it, let's do it.","Richard Branson"],
["Business opportunities are like buses, there's always another one coming.","Richard Branson"],
["The brave may not live forever, but the cautious do not live at all.","Richard Branson"],
["Train people well enough so they can leave, treat them well enough so they don't want to.","Richard Branson"],
["If somebody offers you an amazing opportunity and you're not sure you can do it, say yes — then learn how to do it later.","Richard Branson"],
["The biggest adventure you can take is to live the life of your dreams.","Oprah Winfrey"],
["Turn your wounds into wisdom.","Oprah Winfrey"],
// 221–230 · Oprah, Angelou & Twain
["Doing the best at this moment puts you in the best place for the next moment.","Oprah Winfrey"],
["You become what you believe.","Oprah Winfrey"],
["Nothing will work unless you do.","Maya Angelou"],
["If you don't like something, change it. If you can't change it, change your attitude.","Maya Angelou"],
["We may encounter many defeats but we must not be defeated.","Maya Angelou"],
["Success is liking yourself, liking what you do, and liking how you do it.","Maya Angelou"],
["The secret of getting ahead is getting started.","Mark Twain"],
["Twenty years from now you will be more disappointed by the things you didn't do than by the ones you did.","Mark Twain"],
["Courage is resistance to fear, mastery of fear — not absence of fear.","Mark Twain"],
["Continuous improvement is better than delayed perfection.","Mark Twain"],
// 231–240 · Twain & Churchill
["The two most important days in your life are the day you are born and the day you find out why.","Mark Twain"],
["The world owes you nothing. It was here first.","Mark Twain"],
["Whenever you find yourself on the side of the majority, it is time to pause and reflect.","Mark Twain"],
["Success is not final, failure is not fatal: it is the courage to continue that counts.","Winston Churchill"],
["Never, never, never give up.","Winston Churchill"],
["Attitude is a little thing that makes a big difference.","Winston Churchill"],
["If you're going through hell, keep going.","Winston Churchill"],
["Success consists of going from failure to failure without loss of enthusiasm.","Winston Churchill"],
["We make a living by what we get, but we make a life by what we give.","Winston Churchill"],
["Continuous effort — not strength or intelligence — is the key to unlocking our potential.","Winston Churchill"],
// 241–250 · Roosevelt & Lincoln
["Do what you can, with what you have, where you are.","Theodore Roosevelt"],
["Believe you can and you're halfway there.","Theodore Roosevelt"],
["It is hard to fail, but it is worse never to have tried to succeed.","Theodore Roosevelt"],
["The credit belongs to the man who is actually in the arena.","Theodore Roosevelt"],
["The best prize that life offers is the chance to work hard at work worth doing.","Theodore Roosevelt"],
["The best way to predict your future is to create it.","Abraham Lincoln"],
["Give me six hours to chop down a tree and I will spend the first four sharpening the axe.","Abraham Lincoln"],
["Whatever you are, be a good one.","Abraham Lincoln"],
["I am a slow walker, but I never walk back.","Abraham Lincoln"],
["Your own resolution to succeed is more important than any other.","Abraham Lincoln"],
// 251–260 · Lombardi, Kobe & Jordan
["Winners never quit and quitters never win.","Vince Lombardi"],
["Perfection is not attainable, but if we chase perfection we can catch excellence.","Vince Lombardi"],
["The only place success comes before work is in the dictionary.","Vince Lombardi"],
["It's not whether you get knocked down, it's whether you get up.","Vince Lombardi"],
["Everything negative — pressure, challenges — is all an opportunity for me to rise.","Kobe Bryant"],
["The moment you give up is the moment you let someone else win.","Kobe Bryant"],
["Great things come from hard work and perseverance. No excuses.","Kobe Bryant"],
["Rest at the end, not in the middle.","Kobe Bryant"],
["I've failed over and over and over again in my life. And that is why I succeed.","Michael Jordan"],
["If you run into a wall, don't turn around and give up. Figure out how to climb it.","Michael Jordan"],
// 261–270 · Jordan, Ali & Founders-podcast favorites
["Some people want it to happen, some wish it would happen, others make it happen.","Michael Jordan"],
["Limits, like fears, are often just an illusion.","Michael Jordan"],
["Don't count the days, make the days count.","Muhammad Ali"],
["He who is not courageous enough to take risks will accomplish nothing in life.","Muhammad Ali"],
["Suffer now and live the rest of your life as a champion.","Muhammad Ali"],
["Impossible is just a big word thrown around by small men.","Muhammad Ali"],
["Belief comes before ability.","David Senra"],
["Excellence is the capacity to take pain.","Isadore Sharp"],
["There is no speed limit.","Derek Sivers"],
["Whatever you do, do it with all your might. Work at it early and late, in season and out of season.","P.T. Barnum"],
// 271–280 · Founders & startup wisdom
["Sell cheap and tell the truth.","Rose Blumkin"],
["Competition is for losers.","Peter Thiel"],
["What important truth do very few people agree with you on?","Peter Thiel"],
["A startup is the largest endeavor over which you can have definite mastery.","Peter Thiel"],
["Startups rarely die when they run out of money; they die when the founders give up.","Paul Graham"],
["Do things that don't scale.","Paul Graham"],
["The way to do really big things is to start with deceptively small things.","Paul Graham"],
["It's hard to do a really good job on anything you don't think about in the shower.","Paul Graham"],
["Make something people want.","Paul Graham"],
["An entrepreneur is someone who jumps off a cliff and builds a plane on the way down.","Reid Hoffman"],
// 281–290 · Hoffman, Gates & Rohn
["If you are not embarrassed by the first version of your product, you've launched too late.","Reid Hoffman"],
["Most people overestimate what they can do in one year and underestimate what they can do in ten.","Bill Gates"],
["Success is a lousy teacher. It seduces smart people into thinking they can't lose.","Bill Gates"],
["Your most unhappy customers are your greatest source of learning.","Bill Gates"],
["Discipline is the bridge between goals and accomplishment.","Jim Rohn"],
["Motivation is what gets you started. Habit is what keeps you going.","Jim Rohn"],
["You are the average of the five people you spend the most time with.","Jim Rohn"],
["Either you run the day or the day runs you.","Jim Rohn"],
["Success is nothing more than a few simple disciplines, practiced every day.","Jim Rohn"],
["Don't wish it were easier, wish you were better.","Jim Rohn"],
// 291–300 · Ziglar & Napoleon Hill
["You don't have to be great to start, but you have to start to be great.","Zig Ziglar"],
["Motivation doesn't last. Neither does bathing — that's why we recommend it daily.","Zig Ziglar"],
["There are no traffic jams along the extra mile.","Zig Ziglar"],
["If you aim at nothing, you will hit it every time.","Zig Ziglar"],
["Whatever the mind can conceive and believe, it can achieve.","Napoleon Hill"],
["Don't wait. The time will never be just right.","Napoleon Hill"],
["Strength and growth come only through continuous effort and struggle.","Napoleon Hill"],
["A goal is a dream with a deadline.","Napoleon Hill"],
["The starting point of all achievement is desire.","Napoleon Hill"],
["Patience, persistence and perspiration make an unbeatable combination for success.","Napoleon Hill"],
// 301–310 · Dale Carnegie & Epictetus
["Inaction breeds doubt and fear. Action breeds confidence and courage.","Dale Carnegie"],
["The important things in the world have been accomplished by people who kept on trying when there seemed to be no hope.","Dale Carnegie"],
["Discouragement and failure are two of the surest stepping stones to success.","Dale Carnegie"],
["Today is life — the only life you are sure of. Make the most of today.","Dale Carnegie"],
["It's not what happens to you, but how you react to it that matters.","Epictetus"],
["No man is free who is not master of himself.","Epictetus"],
["First say to yourself what you would be; and then do what you have to do.","Epictetus"],
["Wealth consists not in having great possessions, but in having few wants.","Epictetus"],
["Only the educated are free.","Epictetus"],
["A journey of a thousand miles begins with a single step.","Lao Tzu"],
// 311–320 · Lao Tzu, Socrates & Plato
["When I let go of what I am, I become what I might be.","Lao Tzu"],
["Nature does not hurry, yet everything is accomplished.","Lao Tzu"],
["Mastering others is strength. Mastering yourself is true power.","Lao Tzu"],
["Do the difficult things while they are easy and do the great things while they are small.","Lao Tzu"],
["The secret of change is to focus all of your energy not on fighting the old, but on building the new.","Socrates"],
["The unexamined life is not worth living.","Socrates"],
["The first and greatest victory is to conquer yourself.","Plato"],
["Never discourage anyone who continually makes progress, no matter how slow.","Plato"],
["Optimism is the faith that leads to achievement.","Helen Keller"],
["Life is either a daring adventure or nothing at all.","Helen Keller"],
// 321–333 · Pioneers & scientists
["The future belongs to those who believe in the beauty of their dreams.","Eleanor Roosevelt"],
["Do one thing every day that scares you.","Eleanor Roosevelt"],
["The most effective way to do it, is to do it.","Amelia Earhart"],
["Nothing in life is to be feared, it is only to be understood.","Marie Curie"],
["Be less curious about people and more curious about ideas.","Marie Curie"],
["I was taught that the way of progress was neither swift nor easy.","Marie Curie"],
["If I have seen further it is by standing on the shoulders of giants.","Isaac Newton"],
["It is not the strongest of the species that survives, but the most adaptable to change.","Charles Darwin"],
["However difficult life may seem, there is always something you can do and succeed at.","Stephen Hawking"],
["The most dangerous phrase in the language is, 'We've always done it this way.'","Grace Hopper"],
["A ship in port is safe, but that's not what ships are built for.","Grace Hopper"],
["Do not go where the path may lead, go instead where there is no path and leave a trail.","Ralph Waldo Emerson"],
["Success usually comes to those who are too busy to be looking for it.","Henry David Thoreau"]
];
